VersionRamCustom:29
VersionFabric:0.19.5
State:9
VersionVanillaName:1.20.1
VersionArgumentJavaV2:3
VersionArgumentIndieV2:True
VersionVanilla:20.0.1
VersionRamType:1
Info:正式版 1.20.1, Fabric 0.19.5
VersionLiteLoader:False
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Fabric.png
ReleaseTime:2023-06-12 06:25
